# Generated by Django 6.0.3 on 2026-04-15 11:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('article', 'Статья'), ('news', 'Новость'), ('tutorial', 'Урок')], max_length=50, verbose_name='Тип публикации')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('url_key', models.SlugField(max_length=255, unique=True, verbose_name='URL-ключ')),
                ('preview_description', models.TextField(verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Полный текст')),
                ('featured_image', models.CharField(blank=True, max_length=500, null=True, verbose_name='Главное изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Запись блога',
                'verbose_name_plural': 'Записи блога',
                'db_table': 'blog_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, verbose_name='Название')),
                ('url_key', models.SlugField(max_length=150, unique=True, verbose_name='URL-ключ')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка')),
                ('sort_order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'categories',
                'ordering': ['sort_order', 'category_name'],
            },
        ),
        migrations.CreateModel(
            name='IdeaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby_type', models.CharField(choices=[('рисование', 'Рисование'), ('шитьё', 'Шитьё'), ('вышивание', 'Вышивание'), ('вязание', 'Вязание'), ('валяние', 'Валяние'), ('лепка', 'Лепка'), ('скрапбукинг', 'Скрапбукинг'), ('бисероплетение', 'Бисероплетение'), ('декорирование', 'Декорирование'), ('мыловарение', 'Мыловарение'), ('свечеварение', 'Свечеварение'), ('флористика', 'Флористика'), ('эпоксидная смола', 'Эпоксидная смола'), ('кулинария', 'Кулинария')], max_length=100, verbose_name='Тип хобби')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('idea_description', models.TextField(verbose_name='Описание')),
                ('result_image', models.CharField(blank=True, max_length=500, null=True, verbose_name='Фото результата')),
                ('product_ids', models.JSONField(verbose_name='ID товаров')),
                ('sort_order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Порядок')),
                ('age_group', models.CharField(blank=True, choices=[('дети', 'Дети'), ('молодежь', 'Молодежь'), ('взрослые', 'Взрослые'), ('все', 'Все')], max_length=50, null=True, verbose_name='Возрастная группа')),
                ('difficulty', models.CharField(blank=True, choices=[('легкий', 'Легкий'), ('средний', 'Средний'), ('сложный', 'Сложный')], max_length=50, null=True, verbose_name='Сложность')),
            ],
            options={
                'verbose_name': 'Шаблон идеи',
                'verbose_name_plural': 'Шаблоны идей',
                'db_table': 'idea_templates',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название')),
                ('url_key', models.SlugField(max_length=255, unique=True, verbose_name='URL-ключ')),
                ('product_description', models.TextField(verbose_name='Описание')),
                ('attributes', models.JSONField(blank=True, null=True, verbose_name='Характеристики')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('old_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Старая цена')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Остаток')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('reviews_count', models.IntegerField(default=0, verbose_name='Количество отзывов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, choices=[('мужской', 'Мужской'), ('женский', 'Женский')], max_length=10, null=True, verbose_name='Пол')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('avatar', models.CharField(blank=True, max_length=500, null=True, verbose_name='Аватар')),
                ('user_role', models.CharField(choices=[('customer', 'Покупатель'), ('admin', 'Администратор')], default='customer', max_length=50, verbose_name='Роль')),
                ('email_notifications_enabled', models.BooleanField(default=False, verbose_name='Email-уведомления')),
                ('notify_order_status', models.BooleanField(default=True, verbose_name='Статус заказа')),
                ('notify_promo', models.BooleanField(default=False, verbose_name='Акции и скидки')),
                ('notify_system', models.BooleanField(default=True, verbose_name='Системные уведомления')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AiChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(verbose_name='ID сессии')),
                ('hobby_type', models.CharField(choices=[('рисование', 'Рисование'), ('шитьё', 'Шитьё'), ('вышивание', 'Вышивание'), ('вязание', 'Вязание'), ('валяние', 'Валяние'), ('лепка', 'Лепка'), ('скрапбукинг', 'Скрапбукинг'), ('бисероплетение', 'Бисероплетение'), ('декорирование', 'Декорирование'), ('мыловарение', 'Мыловарение'), ('свечеварение', 'Свечеварение'), ('флористика', 'Флористика'), ('эпоксидная смола', 'Эпоксидная смола'), ('кулинария', 'Кулинария')], max_length=100, verbose_name='Тип хобби')),
                ('age_group', models.CharField(choices=[('дети', 'Дети'), ('молодежь', 'Молодежь'), ('взрослые', 'Взрослые'), ('все', 'Все')], max_length=50, verbose_name='Возрастная группа')),
                ('difficulty', models.CharField(choices=[('легкий', 'Легкий'), ('средний', 'Средний'), ('сложный', 'Сложный')], max_length=50, verbose_name='Сложность')),
                ('ai_response', models.TextField(verbose_name='Ответ ИИ')),
                ('suggested_products', models.JSONField(blank=True, null=True, verbose_name='Предложенные товары')),
                ('was_accepted', models.BooleanField(default=False, verbose_name='Добавлено в корзину')),
                ('was_regenerated', models.BooleanField(default=False, verbose_name='Перегенерировано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение чата с ИИ',
                'verbose_name_plural': 'Сообщения чата с ИИ',
                'db_table': 'ai_chat_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_status', 'Статус заказа'), ('promo', 'Акция'), ('system', 'Системное'), ('reminder', 'Напоминание')], max_length=50, verbose_name='Тип')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('notification_message', models.TextField(verbose_name='Сообщение')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Отправлено на email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Номер заказа')),
                ('order_status', models.CharField(choices=[('новый', 'Новый'), ('в обработке', 'В обработке'), ('оплачен', 'Оплачен'), ('отправлен', 'Отправлен'), ('доставлен', 'Доставлен'), ('отменён', 'Отменён')], default='новый', max_length=50, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('recipient_full_name', models.CharField(max_length=255, verbose_name='Получатель')),
                ('recipient_email', models.EmailField(max_length=255, verbose_name='Email получателя')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='Телефон получателя')),
                ('delivery_address', models.TextField(verbose_name='Адрес доставки')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата доставки')),
                ('delivery_time_slot', models.CharField(blank=True, max_length=20, null=True, verbose_name='Временной слот')),
                ('payment_method', models.CharField(choices=[('картой онлайн', 'Картой онлайн'), ('наличными при получении', 'Наличными при получении'), ('картой при получении', 'Картой при получении')], max_length=50, verbose_name='Способ оплаты')),
                ('payment_status', models.CharField(choices=[('в процессе', 'В процессе'), ('оплачено', 'Оплачено'), ('ошибка', 'Ошибка')], default='в процессе', max_length=50, verbose_name='Статус оплаты')),
                ('customer_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Количество')),
                ('product_image', models.CharField(blank=True, max_length=500, null=True, verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='api.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказах',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt-текст')),
                ('sort_order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фото товаров',
                'db_table': 'product_images',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=150, verbose_name='Название')),
                ('url_key', models.SlugField(max_length=150, verbose_name='URL-ключ')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка')),
                ('sort_order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'db_table': 'subcategories',
                'ordering': ['category__sort_order', 'sort_order', 'subcategory_name'],
                'unique_together': {('category', 'url_key')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'db_table': 'favorites',
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Количество')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='api.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Товары в корзине',
                'db_table': 'cart_items',
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('user_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('moderation', 'На модерации'), ('approved', 'Опубликован'), ('rejected', 'Отклонён')], default='moderation', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.product', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
    ]
